### PR TITLE
fix server pids not beeing captured

### LINKED ISSUE #243: Error messages when exiting nix-shell
When I exit `nix-shell` after running out shell scripts I see the following output. We shouldn't print `panic` messages because the developer might think they did something wrong. Perhaps we could with kill processes in reverse order so that `server` instances are killed before `bitcoind` / `lightningd`? 

<details>
  <summary>logs ...</summary>
  
```
exit
2022-07-11T14:56:42Z tor: Thread interrupt
2022-07-11T14:56:42Z torcontrol thread exit
2022-07-11T14:56:42Z Shutdown: In progress...
2022-07-11T14:56:42Z opencon thread exit
2022-07-11T14:56:42Z addcon thread exit
2022-07-11T14:56:42Z msghand thread exit
Lost connection to the RPC socket.
Lost connection to the RPC socket.
Lost connection to the RPC socket.
2022-07-11T14:56:42Z net thread exit
Justins-MacBook-Pro% 2022-07-11T14:56:42Z DumpAnchors: Flush 0 outbound block-relay-only peer addresses to anchors.dat started
2022-07-11T14:56:42Z DumpAnchors: Flush 0 outbound block-relay-only peer addresses to anchors.dat completed (0.02s)
2022-07-11T14:56:42Z scheduler thread exit
2022-07-11T14:56:42Z Writing 0 unbroadcast transactions to disk.
2022-07-11T14:56:42Z Dumped mempool: 2.5e-05s to copy, 0.018449s to dump
mint 3: thread 'main' panicked at 'Bitcoind returned an error: JsonRpc(Transport(SocketError(Os { code: 61, kind: ConnectionRefused, message: "Connection refused" })))', modules/minimint-wallet/src/bitcoincore_rpc.rs:36:14
mint 3: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
mint 3: thread 'tokio-runtime-worker' panicked at 'Peer connection was droppedthread 'tokio-runtime-worker' panicked at 'Peer connection was dropped', /Users/justin/ecash/minimint/minimint/src/net/peers.rs', /Users/justin/ecash/minimint/minimint/src/net/peers.rs:311:37
mint 3: :311:37
mint 1: thread 'main' panicked at 'Bitcoind returned an error: JsonRpc(Transport(SocketError(Os { code: 61, kind: ConnectionRefused, message: "Connection refused" })))', modules/minimint-wallet/src/bitcoincore_rpc.rs:36:14
mint 1: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
mint 1: thread 'tokio-runtime-worker' panicked at 'Peer connection was dropped', /Users/justin/ecash/minimint/minimint/src/net/peers.rs:311:37
mint 1: thread 'tokio-runtime-worker' panicked at 'Peer connection was dropped', /Users/justin/ecash/minimint/minimint/src/net/peers.rs:311:37
mint 1: thread 'tokio-runtime-worker' panicked at 'Peer connection was dropped', /Users/justin/ecash/minimint/minimint/src/net/peers.rs:311:37
2022-07-11T14:56:42Z [default wallet] Releasing wallet
2022-07-11T14:56:42Z Shutdown: done
mint 0: thread 'main' panicked at 'Bitcoind returned an error: JsonRpc(Transport(SocketError(Os { code: 61, kind: ConnectionRefused, message: "Connection refused" })))', modules/minimint-wallet/src/bitcoincore_rpc.rs:36:14
mint 0: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
mint 0: thread 'thread 'tokio-runtime-workertokio-runtime-worker' panicked at '' panicked at 'Peer connection was droppedPeer connection was dropped', ', /Users/justin/ecash/minimint/minimint/src/net/peers.rs:311:37
mint 0: /Users/justin/ecash/minimint/minimint/src/net/peers.rs:311:37
mint 2: thread 'main' panicked at 'Bitcoind returned an error: JsonRpc(Transport(SocketError(Os { code: 61, kind: ConnectionRefused, message: "Connection refused" })))', modules/minimint-wallet/src/bitcoincore_rpc.rs:36:14
mint 2: note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
mint 2: thread 'tokio-runtime-worker' panicked at 'Peer connection was dropped', /Users/justin/ecash/minimint/minimint/src/net/peers.rs:311:37
mint 2: thread 'tokio-runtime-worker' panicked at 'Peer connection was dropped', /Users/justin/ecash/minimint/minimint/src/net/peers.rs:311:37
```

</details>

Also, it seems like the PIDs of the `server` processes are never written to our `.pid` file. Seems like [these two lines](https://github.com/fedimint/minimint/blob/master/scripts/start-fed.sh#L12) fail. I mention here because killing processes in reverse order won't work if the `panic`'ing process PIDs aren't in our PID file!

### PR DESCRIPTION
**Pull request by NicolaLS**
Fixes #243

### CODE REVIEW

File: scripts/build.sh [hunk 1]
```diff
@@ -14,7 +14,7 @@ cargo build --release
 # Define temporary directories to not overwrite manually created config if run locally
 export MINIMINT_TEST_DIR=$TMP_DIR
 export BIN_DIR="$SRC_DIR/target/release"
-export PID_FILE=".pid"
+export PID_FILE="$TMP_DIR/.pid"
```
Comment (jkitman) [inline scripts/build.sh:17]: Was this just to put all tmp files into the same dir?

File: scripts/start-fed.sh [hunk 2]
```diff
@@ -9,6 +9,5 @@ SKIPPED_SERVERS=${SKIPPED_SERVERS:-0}
 cd $CFG_DIR
 for ((ID=SKIPPED_SERVERS; ID<FED_SIZE; ID++)); do
   echo "starting mint $ID"
-  ($BIN_DIR/server $CFG_DIR/server-$ID.json 2>&1 | sed -e "s/^/mint $ID: /" ) &
-  echo $! >> $PID_FILE
+  ( ($BIN_DIR/server $CFG_DIR/server-$ID.json 2>&1 & echo $! >&3 ) 3>>$PID_FILE | sed -e "s/^/mint $ID: /" ) &
```
Comment (jkitman) [inline scripts/start-fed.sh:12]: I see, so this puts the PIDs at the end of the file after the server process ends?

**Review by jkitman — COMMENTED** [review]
Seems like a reasonable solution would be even nicer if you could figure out how to kill the `ln_gateway`.  Also wondering if there would be even less error messages if `lightningd` was killed before `bitcoind`?

**Comment by justinmoon** [comment]
>  would be even nicer if you could figure out how to kill the ln_gateway

Yes. I've noticed that sometimes it seems to continue to run after `lightningd` has been stopped.

File: scripts/start-fed.sh (hunk 2 above)
Comment (NicolaLS) [reply scripts/start-fed.sh:12]: I think the braces `( cmd1 > 1 & cmd2 >3) | sed uses 1` make the commands "share" the stdout and sed just cares for 1

**Comment by NicolaLS** [comment]
> > would be even nicer if you could figure out how to kill the ln_gateway
> 
> Yes. I've noticed that sometimes it seems to continue to run after `lightningd` has been stopped.

added `kill $(pidof "ln_gateway")` it's a bit lazy but I think checking for it running etc would be an overkill ?

File: scripts/start-fed.sh (hunk 2 above)
Comment (jkitman) [reply scripts/start-fed.sh:12]: What was the stackoverflow post?

The server should be redirecting std error to std output with `2>&1` then run the background, which makes sense since the server still outputs while running.  I expected something like `2>/dev/null` if it was suppressing the error messages.  Could it be something like it outputs the PID in the background now so the server PIDs end up at the end of the PID_FILE?

Comment (jkitman) [reply scripts/start-fed.sh:12]: My suggestion is let's just write `server`, `lightningd` and `bitcoind` PIDs to different PID files then close them in that order.

Comment (NicolaLS) [reply scripts/start-fed.sh:12]: [this](https://stackoverflow.com/questions/1652680/how-to-get-the-pid-of-a-process-that-is-piped-to-another-process-in-bash). I'm not sure if I understand what you mean. But yes that sounds like a good idea (can push this in abt 4hrs have to go now)

Comment (jkitman) [reply scripts/start-fed.sh:12]: So just write the `bitcoind` PID to `$TMP_DIR/.pid_bitcoind` etc.  Then in the `kill_minimint_processes` function we can read from the PID files in the order we want the services killed, which should be server, lightningd then bitcoind

Comment (jkitman) [reply scripts/start-fed.sh:12]: Ah NVM I was thinking this was related to a different issue.

**Review by jkitman — APPROVED** [review]
I'm okay with this so long as @justinmoon doesn't know a better solution than
```kill $(pidof "ln_gateway")```

File: scripts/build.sh [hunk 3]
```diff
@@ -43,9 +43,8 @@ alias mint_rpc_client="\$MINT_RPC_CLIENT"
 
 # Function for killing processes stored in PID_FILE
 function kill_minimint_processes {
-  while read pid; do
-    kill $pid || true
-  done <$PID_FILE
+  kill $(cat $PID_FILE | sed '1!G;h;$!d') #sed reverses the order here
+  kill $(pidof "ln_gateway")
```
Comment (elsirion) [inline scripts/build.sh:47]: I assume that could be a call to `pkill`? Also, doesn't `lightningd` take care of its plugins?

**Review by elsirion — APPROVED** [review]
Looks good, just a minor nit. And oh boy is that usage of `sed` a nice hack :laughing:

**Review by elsirion — APPROVED** [review]
